### ISSUE TITLE
Update the url in homepage

### ISSUE THREAD

**Issue by Aslemammad** [tinylibs/tinylibs.github.io#1]
the current url does not work.

**Comment by jcbhmr** [comment]
You mean the url on the repo sidebar that's currently https://jcbhmr.github.io/somethingsomething? Yeah that was when it was under @jcbhmr. That should be changed to https://tinylibs.github.io which is the new GitHub pages url that it's deployed to. 

I actually don't have the permission to do this lmao 🤣 since I Transferred it and lost perms. @Aslemammad you can change the website, description, and tags via clicking ⚙️ on the top of the right side bar when viewing the Code tab of this repo

**Comment by Aslemammad** [comment]
Thanks, yea, let's change it.
